[package]
name = "tengwar"
description = "Transcribe romanized text into J.R.R. Tolkien's Tengwar."
version = "0.1.0"

authors = ["Yaulendil <davarice@protonmail.com>"]
repository = "https://github.com/yaulendil/tengwar-rs"
readme = "README.md"

exclude = ["/.idea", "*.txt"]
categories = ["command-line-utilities", "text-processing"]
keywords = ["text", "unicode", "tengwar", "quenya"]

edition = "2018"
license = "Apache-2.0"


[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"


[dependencies]
itertools = "0.10.0"


[features]
long-vowel-double = []
long-vowel-unique = []
